server:
  port: 8081

spring:
  application:
    name: user-service
  servlet:
    multipart:
      max-file-size: 5MB
jwt:
  secret: jaklsdj1283e7osalkd
  expiration: 36000 #10 * 60 * 60 (10 hours)
  longExpiration: 604800 #7 * 24 * 60 * 60 (7 days)
  defaultPassword: 123@456
